- name: Check if Tarsnap is installed
  command: tarsnap --version
  register: tarsnap_installed
  changed_when: tarsnap_installed.rc != 0
  ignore_errors: yes
  tags:
    - dependencies

- name: Install dependencies for Tarsnap
  when: tarsnap_installed is failed
  apt:
    name: lsb-release
  tags:
    - dependencies

- name: Download the current tarsnap deb packaging key
  when: tarsnap_installed is failed
  get_url:
    url=https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc
    dest=/root/tarsnap-deb-packaging-key.asc

- name: Add the tarsnap code signing key to your list of keys
  when: tarsnap_installed is failed
  apt_key:
    file: /root/tarsnap-deb-packaging-key.asc

- name: Add the Tarsnap binary package repository
  when: tarsnap_installed is failed
  apt_repository: repo="deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"

- name: Install Tarsnap binary package
  when: tarsnap_installed is failed
  apt:
    name: tarsnap
    update_cache: yes

- name: Copy Tarsnap key file into place
  copy: src=decrypted_tarsnap.key dest=/decrypted/tarsnap.key owner=root group=root mode="0600" force=no

- name: Create Tarsnap cache directory
  file: state=directory path=/usr/tarsnap-cache

- name: Install Tarsnap configuration file
  copy: src=tarsnaprc dest=/root/.tarsnaprc mode="0644"

- name: Install Tarsnap backup handler script
  copy: src=tarsnap.sh dest=/root/tarsnap.sh mode="0755"

- name: Install nightly Tarsnap-generations cronjob
  cron: name="Tarsnap backup" hour="3" minute="0" job="sh /root/tarsnap.sh >> /var/log/tarsnap.log"
